import tkinter as tk
from tkinter import messagebox


class Connect4:
    def __init__(self, rows=6, cols=7):
        self.rows = rows
        self.cols = cols
        self.board = None
        self.scores = {1: 0, 2: 0}  # 1: human, 2: AI

    def initialize_board(self):
        self.board = [[0 for _ in range(self.cols)] for _ in range(self.rows)]

    def play(self, col, player):
        for row in range(self.rows - 1, -1, -1):
            if self.board[row][col] == 0:
                self.board[row][col] = player
                self.update_scores(player, row, col)
                return True
        return False

    def is_valid_move(self, col):
        # column is in the range of the board and column is not full
        return 0 <= col < self.cols and self.board[0][col] == 0

    def get_valid_moves(self):
        # returns a list of columns that are  available according to if the column is full or not
        # the function that checks for the condition is the is valid move function
        return [col for col in range(self.cols) if self.is_valid_move(col)]

    def get_children(self, player):
        children = []
        # generate the children the states are generated by inserting a disc for the human in each valid column
        for col in self.get_valid_moves():
            child_board = [row[:] for row in self.board]  # Deep copy of the board

            # moves on rows from down to top and inserts the disc where the cell is empty  and then
            #  adds the child to the children and the corresponding column
            for row in range(self.rows - 1, -1, -1):
                if child_board[row][col] == 0:
                    child_board[row][col] = player
                    break
            children.append((child_board, col))
        return children

    def is_full(self):
        return all(all(cell != 0 for cell in row) for row in self.board)

    def update_scores(self, player, row, col):
        directions = [(0, 1), (1, 0), (1, 1), (1, -1)]
        for dr, dc in directions:
            count = 1
            for sign in [-1, 1]:
                r, c = row, col
                while 0 <= r + dr * sign < self.rows and 0 <= c + dc * sign < self.cols:
                    r, c = r + dr * sign, c + dc * sign
                    if self.board[r][c] == player:
                        count += 1
                        if count == 4:
                            self.scores[player] += 1
                            break
                    else:
                        break

    def print_board(self):
        print("\nCurrent Board:")
        for row in self.board:
            print(' '.join(str(cell) for cell in row))
        print("\n")

    def get_cell(self, row, col):
        return self.board[row][col]

    def set_cell(self, row, col, value):
        self.board[row][col] = value




def generate_positional_scores(rows, cols):
    scores = [[0 for _ in range(cols)] for _ in range(rows)]
    mid_row, mid_col = rows // 2, cols // 2
    for row in range(rows):
        for col in range(cols):
            scores[row][col] = rows + cols - (abs(row - mid_row) + abs(col - mid_col))
    return scores


def calculate_positional_advantage(board, player):
    rows = len(board)
    cols = len(board[0])
    position_scores = generate_positional_scores(rows, cols)
    score = 0

    for i in range(rows):
        for j in range(cols):
            if board[i][j] == player:
                score += position_scores[i][j]
    return score


def search_direction(board, length, direction, row, col, player):
    rows = len(board)
    cols = len(board[0])
    change_x, change_y = direction
    for k in range(length):
        new_row = row + k * change_x
        new_col = col + k * change_y
        if new_row < 0 or new_row >= rows or new_col < 0 or new_col >= cols:
            return 0
        if board[new_row][new_col] != player:
            return 0
    return 1
def count_connected_N(board, player, length):
    count = 0
    directions = {
        "vertical": (0, 1),
        "horizontal": (1, 0),
        "positivediagonal": (1, 1),
        "negativediagonal": (1, -1)
    }
    rows = len(board)
    cols = len(board[0])
    
    for row in range(rows):
        for col in range(cols):
            for direction in directions.values():
                if length == 4:
                    count += search_direction(board, length, direction, row, col, player)
                elif length == 2 or length == 3:
                    count += check_potential_sequence(board, player, row, col, length, direction)
    return count

def check_potential_sequence(board, player, row, col, length, direction):
    count = 0
    directions = direction
    empty_spots = 0
    rows = len(board)
    cols = len(board[0])

    for sign in [-1, 1]:
        r, c = row, col
        sequence = []

        for i in range(length + 1): 
            r, c = r + sign * directions[0], c + sign * directions[1]
            if 0 <= r < rows and 0 <= c < cols:
                if board[r][c] == player:
                    sequence.append(1) 
                elif board[r][c] == 0:
                    sequence.append(0) 
                    empty_spots += 1 
                else:
                    break
            else:
                break
        if len(sequence) == length + 1 and empty_spots == 1:
            count += 1

    return count


def adjust_weights(board):
    rows = len(board)
    cols = len(board[0])
    filled_cells = sum(cell != 0 for row in board for cell in row)
    total_cells = rows * cols
    fill_percentage = filled_cells / total_cells

    if fill_percentage < 0.33:  # Early game
        return {"fours": 50, "threes": 20, "twos": 10, "position": 30}
    elif fill_percentage < 0.66:  # Mid-game
        return {"fours": 100, "threes": 50, "twos": 10, "position": 10}
    else:  # Late game
        return {"fours": 1000, "threes": 200, "twos": 0, "position": 5}


def eval_state(board):
    # Heuristic function to evaluate the state of the board
    
    # Calculate the AI's connected fours, threes, and twos
    ai_connected_four = count_connected_N(board, 2, 4)
    ai_connected_three = count_connected_N(board, 2, 3)
    ai_connected_two = count_connected_N(board, 2, 2)
    
    # Calculate the human's connected fours, threes, and twos
    human_connected_four = count_connected_N(board, 1, 4)
    human_connected_three = count_connected_N(board, 1, 3)
    human_connected_two = count_connected_N(board, 1, 2)
    
    # Calculate AI's positional advantage
    ai_positional_advantage = calculate_positional_advantage(board, 2)
    
    # Get the weights based on the board state
    weights = adjust_weights(board)
    
    # Calculate the AI's score
    ai_score = (
        weights["fours"] * ai_connected_four +
        weights["threes"] * ai_connected_three +
        weights["twos"] * ai_connected_two +
        weights["position"] * ai_positional_advantage
    )
    
    # Calculate the human's score
    human_score = (
        weights["fours"] * human_connected_four +
        weights["threes"] * human_connected_three +
        weights["twos"] * human_connected_two +
        weights["position"] * calculate_positional_advantage(board, 1)
    )

    return ai_score - human_score



def search_direction(board, length, direction, row, col, player):
    rows = len(board)
    cols = len(board[0])
    change_x, change_y = direction
    for k in range(length):
        new_row = row + k * change_x
        new_col = col + k * change_y
        if new_row < 0 or new_row >= rows or new_col < 0 or new_col >= cols:
            return 0
        if board[new_row][new_col] != player:
            return 0
    return 1


def count_connected_N(board, player, length):
    count=0
    directions={
        "vertical":(0,1),
        "horizontal":(1,0),
        "positivediagonal":(1,1),
        "negativediagonal":(-1,-1)
    }
    rows=len(board)
    cols=len(board[0])
    for row in range(rows):
        for col in range(cols):
           for direction in directions.values():
            count+=search_direction(board,length,direction,row,col,player)

    return count


def terminal_test(board):
    return all(all(cell != 0 for cell in row) for row in board)


class game_algorithms:

    def __init__(self):
        self.Is_pruning = False
        self.use_expectiminimax = False

    def minimize(self, board, depth, alpha=float('-inf'), beta=float('inf')):
        if terminal_test(board) or depth == 0:
            return None, eval_state(board)
        
        min_child = None
        min_utility = float('inf')
        temp_game = Connect4()
        temp_game.board = board
        
        for child_board, col in temp_game.get_children(1):
            _, utility = self.maximize(child_board, depth - 1, alpha, beta)
            if utility < min_utility:
                min_child = col
                min_utility = utility
            
            if self.Is_pruning:
                if min_utility <= alpha:
                    break
                beta = min(min_utility, beta)
        
        return min_child, min_utility

    def maximize(self, board, depth, alpha=float('-inf'), beta=float('inf')):
        if terminal_test(board) or depth == 0:
            return None, eval_state(board)
        
        max_child = None
        max_utility = -float('inf')
        temp_game = Connect4()
        temp_game.board = board
        
        for child_board, col in temp_game.get_children(2):
            _, utility = self.minimize(child_board, depth - 1, alpha, beta)
            if utility > max_utility:
                max_child = col
                max_utility = utility
            
            if self.Is_pruning:
                if max_utility >= beta:
                    break
                alpha = max(max_utility, alpha)
        
        return max_child, max_utility

    def decision(self, board, depth=4):
        if self.Is_pruning:
            col, _ = self.maximize(board, depth)
        elif self.use_expectiminimax:
            col, _ = self.expectiminimax(board, depth, 2)
        else:
            col, _ = self.maximize(board, depth)
        return col


class Connect4GUI:
    def __init__(self, root):
        self.root = root
        self.root.title("Connect 4")
        self.game = Connect4()
        self.game.initialize_board()
        self.game_algo = game_algorithms()
        self.buttons = []
        self.cells = []
        
        self.create_board()
        
        # Algorithm selection
        self.algo_frame = tk.Frame(root)
        self.algo_frame.pack(pady=10)
        
        tk.Label(self.algo_frame, text="Algorithm:").pack(side=tk.LEFT)
        self.algo_var = tk.IntVar(value=1)
        tk.Radiobutton(self.algo_frame, text="Minimax", variable=self.algo_var, value=1,
                      command=self.update_algorithm).pack(side=tk.LEFT)
        tk.Radiobutton(self.algo_frame, text="Minimax with Pruning", variable=self.algo_var, value=2,
                      command=self.update_algorithm).pack(side=tk.LEFT)
        tk.Radiobutton(self.algo_frame, text="Expectiminimax", variable=self.algo_var, value=3,
                      command=self.update_algorithm).pack(side=tk.LEFT)
        
        # Score display
        self.score_label = tk.Label(root, text="Scores - Human: 0  AI: 0")
        self.score_label.pack(pady=5)

        # Depth selection
        self.depth_frame = tk.Frame(root)
        self.depth_frame.pack(pady=5)
        tk.Label(self.depth_frame, text="Tree Depth (K):").pack(side=tk.LEFT)
        self.depth_var = tk.StringVar(value="4")
        self.depth_entry = tk.Entry(self.depth_frame, textvariable=self.depth_var, width=5)
        self.depth_entry.pack(side=tk.LEFT)

        # Current player tracking
        self.current_player = 1  # Start with human player
        
        # Player turn label
        self.turn_label = tk.Label(root, text="")
        self.turn_label.pack(pady=5)
        
        self.update_algorithm()
        self.update_turn_label()

    def update_algorithm(self):
        algo_choice = self.algo_var.get()
        self.game_algo.Is_pruning = (algo_choice == 2)
        self.game_algo.use_expectiminimax = (algo_choice == 3)

    def update_turn_label(self):
        player = "Human (Red)" if self.current_player == 1 else "AI (Yellow)"
        self.turn_label.config(text=f"Current Turn: {player}")

    def make_ai_move(self):
        ai_col = self.game_algo.decision(self.game.board, depth=int(self.depth_var.get()))
        self.game.play(ai_col, 2)
        self.update_board()
        self.current_player = 1
        self.update_turn_label()

        if self.game.is_full():
            self.end_game()

    def make_move(self, col):
        if self.current_player != 1:
            return
            
        if not self.game.is_valid_move(col):
            messagebox.showwarning("Invalid Move", "This column is full!")
            return

        self.game.play(col, 1)
        self.update_board()
        
        if self.game.is_full():
            self.end_game()
            return

        self.current_player = 2
        self.update_turn_label()
        self.root.after(1000, self.make_ai_move)

    def create_board(self):
        board_frame = tk.Frame(self.root)
        board_frame.pack(padx=10, pady=10)

        for col in range(self.game.cols):
            btn = tk.Button(board_frame, text="↓", width=4,
                          command=lambda c=col: self.make_move(c))
            btn.grid(row=0, column=col, padx=2)
            self.buttons.append(btn)

        for row in range(self.game.rows):
            row_cells = []
            for col in range(self.game.cols):
                cell = tk.Canvas(board_frame, width=50, height=50,
                               bg='blue', highlightthickness=1)
                cell.grid(row=row+1, column=col, padx=2, pady=2)
                cell.create_oval(5, 5, 45, 45, fill='lightgray')
                row_cells.append(cell)
            self.cells.append(row_cells)

    def update_board(self):
        for row in range(self.game.rows):
            for col in range(self.game.cols):
                color = 'lightgray'
                if self.game.get_cell(row, col) == 1:
                    color = 'red'
                elif self.game.get_cell(row, col) == 2:
                    color = 'yellow'
                self.cells[row][col].create_oval(5, 5, 45, 45, fill=color)
        
        self.score_label.config(text=f"Scores - Human: {self.game.scores[1]}  AI: {self.game.scores[2]}")

    def end_game(self):
        ai_score = self.game.scores[2]
        human_score = self.game.scores[1]
        message = f"Game Over!\nFinal Scores - AI: {ai_score}, Human: {human_score}\n"
        
        if ai_score > human_score:
            message += "AI wins!"
        elif human_score > ai_score:
            message += "You win!"
        else:
            message += "It's a tie!"
            
        messagebox.showinfo("Game Over", message)
        self.root.quit()

def play_game():
    root = tk.Tk()
    gui = Connect4GUI(root)
    root.mainloop()

if __name__ == "__main__":
    play_game()


